######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 3 14:49:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
