######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 22 19:39:12 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
