######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 13 15:30:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imagecollection.h imagedialog.h
FORMS += imagedialog.ui
SOURCES += imagecollection.cpp imagedialog.cpp main.cpp
QT += sql
