######################################################################
# Automatically generated by qmake (2.01a) Mon May 26 22:44:05 2014
######################################################################

TEMPLATE = app
TARGET = d
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buttonbox.h
SOURCES += buttonbox.cpp main.cpp
QT += gui widgets
