######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 9 17:26:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textandnumber.h textdevice.h textthread.h
SOURCES += main.cpp textandnumber.cpp textdevice.cpp textthread.cpp
