######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 5 22:41:23 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textproducerconsumer.h
SOURCES += main.cpp textproducerconsumer.cpp
