######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 21 11:24:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circlebar.h
SOURCES += circlebar.cpp main.cpp
