######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 21 05:20:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += eventwidget.h
SOURCES += eventwidget.cpp main.cpp
