######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 15 23:23:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += eventwidget.h
SOURCES += eventwidget.cpp main.cpp
