######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 23 20:18:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circlewidget.h
SOURCES += circlewidget.cpp main.cpp
