######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 9 14:12:12 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textproducerconsumer.h
SOURCES += main.cpp textproducerconsumer.cpp
