######################################################################
# Automatically generated by qmake (3.0) Wed Jun 4 16:22:41 2014
######################################################################

TEMPLATE = app
TARGET = m
INCLUDEPATH += .

# Input
HEADERS += validationdailog.h
SOURCES += main.cpp validationdailog.cpp
QT += gui widgets
