######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 26 14:20:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myhandler.h
SOURCES += main.cpp myhandler.cpp
QT += xml
