######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 18 17:27:41 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += singleitemview.h
SOURCES += main.cpp singleitemview.cpp
