######################################################################
# Automatically generated by qmake (2.01a) Fri May 23 21:47:47 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += signal_slot.h
SOURCES += main.cpp signal_slot.cpp
