######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 22 09:59:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
