######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 19 15:49:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sender.h
SOURCES += main.cpp sender.cpp
QT += network
