######################################################################
# Automatically generated by qmake (3.0) Thu May 29 16:04:35 2014
######################################################################

TEMPLATE = app
TARGET = h
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui widgets
