######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 13 22:37:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += sql
