######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 18 10:42:31 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bardelegate.h
SOURCES += bardelegate.cpp main.cpp
