######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 19 16:49:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += objecttreemodel.h
SOURCES += main.cpp objecttreemodel.cpp
