######################################################################
# Automatically generated by qmake (3.0) Mon May 26 16:32:05 2014
######################################################################

TEMPLATE = app
TARGET = a
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui widgets
