######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 20 17:43:10 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sortonsecondmodel.h
SOURCES += main.cpp sortonsecondmodel.cpp
