######################################################################
# Automatically generated by qmake (2.01a) Mon May 26 20:09:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
