######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 26 20:11:31 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += infowidget.h sdiwindow.h
SOURCES += infowidget.cpp main.cpp sdiwindow.cpp
