######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 11 12:46:23 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textandnumber.h textdialog.h textthread.h
FORMS += threadingdemo.ui
SOURCES += main.cpp textandnumber.cpp textdialog.cpp textthread.cpp
