######################################################################
# Automatically generated by qmake (2.01a) Mon May 26 20:48:05 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qpushbutton.h
SOURCES += main.cpp qpushbutton.cpp
