######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 17 15:47:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bardelegate.h
SOURCES += bardelegate.cpp main.cpp
