######################################################################
# Automatically generated by qmake (3.0) Tue May 27 15:42:09 2014
######################################################################

TEMPLATE = app
TARGET = g
INCLUDEPATH += .

# Input
HEADERS += listwidgetdialog.h
SOURCES += listwidgetdialog.cpp main.cpp
QT += gui widgets
