######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 21 07:13:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keyboardfilter.h
SOURCES += keyboardfilter.cpp main.cpp
CONFIG += debug
