######################################################################
# Automatically generated by qmake (3.0) Fri May 30 16:29:50 2014
######################################################################

TEMPLATE = app
TARGET = k
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui widgets
