######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 17 11:57:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += httpdialog.h
FORMS += httpdialog.ui
SOURCES += httpdialog.cpp main.cpp
QT += network

