######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 19 14:53:18 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += listener.h
SOURCES += listener.cpp main.cpp
QT += network
