######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 20 16:17:32 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += intmodel.h
SOURCES += intmodel.cpp main.cpp
CONFIG += debug
