######################################################################
# Automatically generated by qmake (3.0) Tue May 27 11:57:08 2014
######################################################################

TEMPLATE = app
TARGET = e
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui widgets
