######################################################################
# Automatically generated by qmake (2.01a) Mon May 26 22:29:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += listdialog.h
FORMS += editdialog.ui listdialog.ui
SOURCES += listdialog.cpp main.cpp
