######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 18 13:10:07 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clientdialog.h
FORMS += clientdialog.ui
SOURCES += clientdialog.cpp main.cpp
QT += network
CONFIG += debug
