######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 11 13:40:42 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += infowidget.h sdiwindow.h
SOURCES += infowidget.cpp main.cpp sdiwindow.cpp
DEFINES += QT_NO_CAST_FROM_ASCII
CONFIG += debug
