######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 23 08:31:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h mybutton.h
FORMS += dialog.ui
SOURCES += dialog.cpp main.cpp mybutton.cpp
