######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 5 11:03:43 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textthread.h
SOURCES += main.cpp textthread.cpp
