######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 15 15:58:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
