######################################################################
# Automatically generated by qmake (3.0) Tue May 27 14:31:07 2014
######################################################################

TEMPLATE = app
TARGET = f
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui widgets
