######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 19 11:03:44 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mulmodel.h
SOURCES += main.cpp mulmodel.cpp
