######################################################################
# Automatically generated by qmake (3.0) Thu May 29 17:08:30 2014
######################################################################

TEMPLATE = app
TARGET = j
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui widgets
