######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 17 13:11:51 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editdialog.h listdialog.h
FORMS += editdialog.ui listdialog.ui
SOURCES += editdialog.cpp listdialog.cpp main.cpp
