######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 11 17:11:35 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
#DEFINES += QT_NO_CAST_FROM_ASCII
