######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 10 19:52:01 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += processdialog.h
FORMS += processdialog.ui
SOURCES += main.cpp processdialog.cpp
CONFIG += debug
