######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 25 11:07:49 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
