######################################################################
# Automatically generated by qmake (2.01a) Sat May 24 13:58:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
