######################################################################
# Automatically generated by qmake (3.0) Fri May 30 17:03:50 2014
######################################################################

TEMPLATE = app
TARGET = l
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui widgets
