######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 18 13:03:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h serverthread.h
SOURCES += main.cpp server.cpp serverthread.cpp

#QT -= gui
QT += network
CONFIG += debug
