######################################################################
# Automatically generated by qmake (2.01a) Sat May 24 22:35:52 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
