######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 25 12:28:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
