######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 21 17:09:03 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clocklabel.h
SOURCES += clocklabel.cpp main.cpp
