######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 26 13:12:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += xml
CONFIG += debug
