######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 11 15:20:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += sql
