######################################################################
# Automatically generated by qmake (2.01a) Sat May 24 10:39:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += signal_slot.h
SOURCES += main.cpp signal_slot.cpp
