######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 15 21:02:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ftpdialog.h
FORMS += ftpdialog.ui
SOURCES += ftpdialog.cpp main.cpp
QT += network
