######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 12 17:28:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
