######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 5 19:52:49 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += increasethread.h textdevice.h textthread.h
SOURCES += increasethread.cpp main.cpp textdevice.cpp textthread.cpp
