######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 3 15:19:56 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
