######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 9 15:39:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textdevice.h textthread.h
SOURCES += main.cpp textdevice.cpp textthread.cpp
